export const CATEGORIES = {
  CLOTHES: 'clothes',
  FOOD: 'food',
  MEDICINE: 'medicine',
  STATIONERY: 'stationery',
  HYGIENE_KITS: 'hygiene_kits',
  ELECTRONICS: 'electronics',
  HOUSEHOLD: 'household',
  BOOKS: 'books',
};

export const CATEGORY_LIST = [
  CATEGORIES.CLOTHES,
  CATEGORIES.FOOD,
  CATEGORIES.MEDICINE,
  CATEGORIES.STATIONERY,
  CATEGORIES.HYGIENE_KITS,
  CATEGORIES.ELECTRONICS,
  CATEGORIES.HOUSEHOLD,
  CATEGORIES.BOOKS,
];

export const NGO_REQUIREMENT_CATEGORY_LIST = [
  CATEGORIES.FOOD,
  CATEGORIES.CLOTHES,
  CATEGORIES.MEDICINE,
  CATEGORIES.STATIONERY,
  CATEGORIES.HYGIENE_KITS,
];

export default CATEGORIES;
